### ISSUE TITLE
vm2 resulting in critical Audit failure for PubNub SDK

### ISSUE THREAD

**Issue by ckotyan** [pubnub/javascript#330]
Our npm audit started failing with critical vulnerability on Vm2 dependency included by (indirectly via proxy-agent) PubNub Javascript SDK (latest 7.x). Not sure if PubNub is aware of it and has  a plan to address this.

https://github.com/advisories/GHSA-g644-9gfx-q4q4

Could you provide ways to fix it?
Thanks
Chandra

**Comment by zymotik** [comment]
The issue lies in [proxy-agent](https://github.com/TooTallNate/proxy-agents) as you mention. Therefore, PubNub would need to wait for [their issue](https://github.com/TooTallNate/proxy-agents/issues/218) to be resolved and released before they can update the pubnub package dependencies.

From my understanding, and correct me if I am wrong, this is a problem if you are using pubnub server side. If you are using the pubnub client in a browser, then proxy agents cannot be used anyway.

**Comment by zymotik** [comment]
To fix this issue, I forked the dependency "superagent-proxy" and changed the code to bypass the undesired functionality. I then used the [npm overrides](https://www.stefanjudis.com/today-i-learned/how-to-override-your-dependencys-dependencies) feature to use our code instead of the vulnerable code.

See instructions in the readme: https://github.com/ezra-virtualvenue-next/superagent-proxy

**Comment by NoriSte** [comment]
They fixed the issue
https://github.com/TooTallNate/proxy-agents/issues/218

and released an updated version 😊
https://github.com/TooTallNate/proxy-agents/releases/tag/proxy-agent%406.3.0

**Comment by parfeon** [comment]
Issue has been addressed, merged and released with #331
